// In-browser load and interaction timings for the 50k-cell scale export (no 200 ms target).
// Usage: node scale_check.mjs <url-of-/multiverse> [chrome|firefox|webkit]
import { chromium, firefox, webkit } from 'playwright';
const [url, which = 'chrome'] = process.argv.slice(2);
const launcher = { chrome: chromium, firefox, webkit }[which];
const browser = await launcher.launch(which === 'chrome' ? { channel: 'chrome' } : {});
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); if (m.text().includes('[multiverse]')) console.log('  ', m.text()); });
const out = {};
let t = Date.now();
await page.goto(url);
await page.waitForSelector('section[aria-labelledby=v0a] svg circle', { timeout: 60000 });
out['entry views rendered (navigation → V0a drawn)'] = Date.now() - t;
t = Date.now();
await page.getByLabel('Colour models by').selectOption('raw:ARI');
await page.waitForFunction(() => document.querySelector('.mv-leaderboard strong')?.textContent?.includes('ARI'));
out['model recolour + leaderboard'] = Date.now() - t;
t = Date.now();
await page.getByRole('tab', { name: /Cells/ }).click();
await page.waitForSelector('#v6', { timeout: 120000 });
await page.waitForFunction(() => document.querySelectorAll('section[aria-labelledby=v6] path').length > 10, null, { timeout: 120000 });
out['cells tab: fetch + parse + first render of V1–V7'] = Date.now() - t;
t = Date.now();
await page.getByLabel('Colour cells by').selectOption('measure:stability_all');
await page.waitForFunction(() => document.querySelector('section[aria-labelledby=v1] .mv-legend-title')?.textContent?.includes('stability'));
out['cell map recolour (hex bins)'] = Date.now() - t;
const c = page.locator('section[aria-labelledby=v1] canvas');
await c.evaluate((e) => e.scrollIntoView({ block: 'center' }));
const b = await c.boundingBox();
await page.mouse.move(b.x + b.width * 0.1, b.y + b.height * 0.1); await page.mouse.down();
for (const [fx, fy] of [[0.6, 0.1], [0.6, 0.6], [0.1, 0.6], [0.1, 0.12]]) await page.mouse.move(b.x + fx * b.width, b.y + fy * b.height, { steps: 4 });
t = Date.now();
await page.mouse.up();
await page.waitForFunction(() => !/all cells/.test(document.querySelector('.mv-selection-summary')?.textContent ?? ''), null, { timeout: 30000 });
out['cell lasso → selection + linked recompute'] = Date.now() - t;
out.selection = await page.locator('.mv-selection-summary').innerText();
out.errors = errors.length ? errors : 'none';
console.log(JSON.stringify(out, null, 1));
await browser.close();
